name: Docker Image CI

on:
  push:
    branches: ['main']
    paths:
      - 'ci/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    # Environment variables
    env:
      DOCKER_HUB_REPO: 'shlomi00212'
      DOCKER_IMAGE_NAME: 'hello-world-app-py'

    steps:
      - uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build the Docker image
      - name: Build the Docker image
        run: docker build ./ci --file ./ci/Dockerfile --tag hello-world-app-py:latest

      # Run container from image
      - name: Run container from image
        run: docker run -d --name hello-world-app-py hello-world-app-py:latest

      - name: Run smoke test
        run: |
          sleep 5
          docker ps -a
          docker logs hello-world-app-py

      # Tag the Docker image with Docker Hub repository name
      - name: Tag the Docker image
        run: docker tag hello-world-app-py:latest ${{ env.DOCKER_HUB_REPO }}/hello-world-app-py:latest

      # Push the Docker image to Docker Hub
      - name: Push the Docker image to Docker Hub
        run: docker push ${{ env.DOCKER_HUB_REPO }}/hello-world-app-py:latest
