name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ci/**'
      - '.github/workflows/ci-cd.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build ./ci --file ./ci/Dockerfile --tag hello-world-app-py:latest

    - name: Run container from image (Smoke Test)
      run: |
        docker run -d --name smoketest_container hello-world-app-py:latest
        sleep 5
        docker ps -a
        docker logs smoketest_container

    # Tag the image with your Docker Hub repository name
    - name: Tag the Docker image
      run: docker tag hello-world-app-py:latest shlomi00212/hello-world-app-py:latest

    # Push the Docker image to Docker Hub
    - name: Push the Docker image to Docker Hub
      run: docker push shlomi00212/hello-world-app-py:latest

