# name: Docker Image CI + SonarQube Scan

# on:
#   push:
#     branches: ['main']
#     paths:
#       - 'ci/**'
#       - '.github/workflows/**'

# jobs:
#   build-and-scan:
#     runs-on: ubuntu-latest

#     env:
#       DOCKER_HUB_REPO: 'shlomi00212'
#       DOCKER_IMAGE_NAME: 'hello-world-app-py'

#     steps:
#       # Checkout the code
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0 # Important: disable shallow clone to improve SonarQube analysis

#       # Log in to Docker Hub
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}

#       # Build the Docker image
#       - name: Build the Docker image
#         run: docker build ./ci --file ./ci/Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:latest

#       # Run the Docker container
#       - name: Run container from the built image
#         run: docker run -d --name ${{ env.DOCKER_IMAGE_NAME }} ${{ env.DOCKER_IMAGE_NAME }}:latest

#       # Run SonarQube scan
#       - name: SonarQube Scan
#         uses: SonarSource/sonarqube-scan-action@v5
#         with:
#           projectBaseDir: ./ci/app
#           args: >
#             -Dsonar.projectKey=test
#             -Dsonar.projectName=test
#             -Dsonar.exclusions=**/myenv/**
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#       # Run a smoke test to verify the container runs correctly
#       - name: Run smoke test
#         run: |
#           sleep 5  #13.60.11.0 Wait for the container to stabilize
#           docker ps -a  # List all containers
#           docker logs ${{ env.DOCKER_IMAGE_NAME }}  # Show logs from the running container

#       # Tag the Docker image for Docker Hub
#       - name: Tag the Docker image
#         run: docker tag ${{ env.DOCKER_IMAGE_NAME }}:latest ${{ env.DOCKER_HUB_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest

#       # Push the Docker image to Docker Hub
#       - name: Push the Docker image
#         run: docker push ${{ env.DOCKER_HUB_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest
name: Docker Image CI + SonarQube Scan

on:
  push:
    branches: ['main']
    paths:
      - 'ci/**'
      - '.github/workflows/**'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_REPO: 'shlomi00212'
      DOCKER_IMAGE_NAME: 'hello-world-app-py'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # חשוב לסריקת blame ב-SonarQube

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build ./ci --file ./ci/Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Run container from built image
        run: docker run -d --name ${{ env.DOCKER_IMAGE_NAME }} ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ./ci/app
          args: >
            -Dsonar.projectKey=test
            -Dsonar.projectName=test
            -Dsonar.sources=.
            -Dsonar.exclusions=**/myenv/**
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # בהתאם למיפוי פורטים שלך, בלי פורט 9000, רק 80
          SONAR_HOST_URL: http://13.60.203.56

      - name: Check if report-task.txt exists and print content
        run: |
          echo "Checking for report-task.txt file:"
          ls -la ./ci/app/.scannerwork/ || echo "Directory not found"
          echo "---"
          cat ./ci/app/.scannerwork/report-task.txt || echo "report-task.txt not found or empty"

      - name: Wait for SonarQube analysis to complete
        run: sleep 30

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: ./ci/app/.scannerwork/report-task.txt
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://13.60.203.56

      - name: Smoke test Check running containers and logs
        run: |
          docker ps -a
          docker logs ${{ env.DOCKER_IMAGE_NAME }}

      - name: Tag Docker image
        run: docker tag ${{ env.DOCKER_IMAGE_NAME }}:latest ${{ env.DOCKER_HUB_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_HUB_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest
